// Auto-generated by json-schema-zod-tools.
import { z } from 'zod';

const BookSchema = z.object({
  author: z.string(),
  genre: z.lazy(() => GenreSchema),
  id: z.uuid(),
  published_at: z.iso.datetime(),
  rating: z.number().min(0).max(5).optional(),
  title: z.string(),
});
const BookCreateSchema = z.object({
  author: z.string(),
  genre: z.lazy(() => GenreSchema),
  published_at: z.union([z.iso.datetime(), z.null()]).optional(),
  title: z.string(),
});
const BookPageSchema = z.object({
  items: z.array(z.lazy(() => BookSchema)),
  page: z.int().min(1),
  size: z.int().min(1),
  total: z.int().min(0),
});
const ErrorSchema = z.object({
  code: z.string(),
  message: z.string(),
});
const GenreSchema = z.enum(['fiction', 'non-fiction', 'science', 'history']);

export const schemas = {
  paths: {
    '/books': {
      get: {
        path: z.object({}),
        query: z.object({
          genre: z.enum(['fiction', 'non-fiction', 'science', 'history']),
          page: z.int().min(1),
          size: z.int().min(1).max(100),
        }),
        responses: {
          '200': z.lazy(() => BookPageSchema),
        },
      },
      post: {
        path: z.object({}),
        query: z.object({}),
        requestBody: {
          'application/json': z.lazy(() => BookCreateSchema),
        },
        responses: {
          '201': z.lazy(() => BookSchema),
        },
      },
    },
    '/books/{id}': {
      get: {
        path: z.object({
          id: z.uuid(),
        }),
        query: z.object({}),
        responses: {
          '200': z.lazy(() => BookSchema),
          '404': z.lazy(() => ErrorSchema),
        },
      },
    },
  },
  components: {
    schemas: {
      Book: BookSchema,
      BookCreate: BookCreateSchema,
      BookPage: BookPageSchema,
      Error: ErrorSchema,
      Genre: GenreSchema,
    },
  },
} as const;
