// Auto-generated by @saunos/openapi-to-zod.
import { z } from 'zod';

const AddressSchema = z.object({
  street: z.string(),
  city: z.string(),
  zip: z.string().regex(new RegExp("^[0-9]{5}$")).optional(),
  country: z.string().min(2).max(2),
});
const AllOfMergedSchema = z.intersection(z.object({
  id: z.string(),
}), z.object({
  name: z.string(),
}));
const ConstantSchema = z.literal("fixed-value");
const EmailSchema = z.email();
const EmptyObjectSchema = z.object({});
const ExclusiveRangeSchema = z.number().gt(0.01).lt(99.99);
const IsoDateSchema = z.iso.date();
const IsoDateTimeSchema = z.iso.datetime();
const LooseObjectSchema = z.looseObject({
  known: z.string().optional(),
});
const MixedEnumSchema = z.union([z.literal(1), z.literal("two"), z.literal(true), z.literal(null)]);
const MultiTypeSchema = z.union([z.string(), z.null()]);
const NullableStringSchema = z.string();
const OneOfVariantsSchema = z.union([z.string().min(1), z.int().min(0)]);
const PortSchema = z.int().min(1).max(65535);
const ScoreSchema = z.number().min(0).max(100).multipleOf(0.5);
const StatusSchema = z.enum(["active", "inactive", "pending"]);
const StrictObjectSchema = z.object({
  key: z.string(),
}).strict();
const StringArraySchema = z.array(z.string());
const StringOrNumberSchema = z.union([z.string(), z.number()]);
const UrlSchema = z.url();
const UserIdSchema = z.uuid();
const CatchallObjectSchema = z.object({
  get id() { return UserIdSchema.optional(); },
}).catchall(z.string());
const TagSchema = z.object({
  get id() { return UserIdSchema; },
  label: z.string(),
}).strict();
const BoundedArraySchema = z.array(TagSchema).min(1).max(10);
const UsernameSchema = z.string().min(3).max(32).regex(new RegExp("^[a-zA-Z0-9_]+$"));
const UserSchema = z.object({
  get id() { return UserIdSchema; },
  get username() { return UsernameSchema; },
  get email() { return EmailSchema; },
  get homepage() { return UrlSchema.optional(); },
  get score() { return ScoreSchema.optional(); },
  get status() { return StatusSchema.optional(); },
  get address() { return AddressSchema.optional(); },
  get tags() { return StringArraySchema.optional(); },
  get createdAt() { return IsoDateTimeSchema; },
  get deletedAt() { return NullableStringSchema.optional(); },
  get friends() { return z.array(UserSchema).optional(); },
});
const PaginatedUsersSchema = z.object({
  get items() { return z.array(UserSchema); },
  total: z.int().min(0),
  nextCursor: z.string().optional(),
});

export const schema = z.object({
  get users() { return PaginatedUsersSchema; },
  get meta() { return z.object({
  version: z.string().optional(),
  get generatedAt() { return IsoDateTimeSchema.optional(); },
}).optional(); },
});
export { schema as ApiResponseSchema };

export const defs = {
  Address: AddressSchema,
  AllOfMerged: AllOfMergedSchema,
  BoundedArray: BoundedArraySchema,
  CatchallObject: CatchallObjectSchema,
  Constant: ConstantSchema,
  Email: EmailSchema,
  EmptyObject: EmptyObjectSchema,
  ExclusiveRange: ExclusiveRangeSchema,
  IsoDate: IsoDateSchema,
  IsoDateTime: IsoDateTimeSchema,
  LooseObject: LooseObjectSchema,
  MixedEnum: MixedEnumSchema,
  MultiType: MultiTypeSchema,
  NullableString: NullableStringSchema,
  OneOfVariants: OneOfVariantsSchema,
  PaginatedUsers: PaginatedUsersSchema,
  Port: PortSchema,
  Score: ScoreSchema,
  Status: StatusSchema,
  StrictObject: StrictObjectSchema,
  StringArray: StringArraySchema,
  StringOrNumber: StringOrNumberSchema,
  Tag: TagSchema,
  Url: UrlSchema,
  User: UserSchema,
  UserId: UserIdSchema,
  Username: UsernameSchema,
} as const;

