import { describe, expect, it } from 'bun:test';

import { generateZodSourceFromJsonSchema } from './json-schema-source-generator';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function generate(
  schema: unknown,
  opts: Parameters<typeof generateZodSourceFromJsonSchema>[1] = {},
) {
  return generateZodSourceFromJsonSchema(schema, { strict: false, ...opts });
}

// ---------------------------------------------------------------------------
// Header
// ---------------------------------------------------------------------------

describe('generateZodSourceFromJsonSchema - header', () => {
  it('emits auto-generated comment and zod import', () => {
    const { code } = generate({ type: 'object', properties: {} });
    expect(code).toContain('// Auto-generated by @saunos/openapi-to-zod.');
    expect(code).toContain("import * as z from 'zod'");
  });
});

// ---------------------------------------------------------------------------
// Root schema export
// ---------------------------------------------------------------------------

describe('generateZodSourceFromJsonSchema - root schema', () => {
  it('exports root object schema', () => {
    const { code } = generate({
      type: 'object',
      required: ['id'],
      properties: {
        id: { type: 'string', format: 'uuid' },
        name: { type: 'string' },
      },
    });
    expect(code).toContain('export const schema =');
    expect(code).toContain('z.object({');
    expect(code).toContain('id: z.uuid()');
    expect(code).toContain('name: z.string().optional()');
  });

  it('exports root string schema', () => {
    const { code } = generate({ type: 'string' });
    expect(code).toContain('export const schema = z.string()');
  });

  it('exports root array schema', () => {
    const { code } = generate({ type: 'array', items: { type: 'number' } });
    expect(code).toContain('export const schema = z.array(z.number())');
  });
});

// ---------------------------------------------------------------------------
// $defs
// ---------------------------------------------------------------------------

describe('generateZodSourceFromJsonSchema - $defs', () => {
  it('emits named const for each $def', () => {
    const { code } = generate({
      type: 'object',
      $defs: {
        Address: {
          type: 'object',
          required: ['street'],
          properties: { street: { type: 'string' } },
        },
      },
      properties: {},
    });
    expect(code).toContain('const AddressSchema =');
    expect(code).toContain('street: z.string()');
  });

  it('exports a defs object containing named schemas', () => {
    const { code } = generate({
      type: 'object',
      $defs: {
        Tag: { type: 'string' },
      },
      properties: {},
    });
    expect(code).toContain('export const defs = {');
    expect(code).toContain('Tag: TagSchema');
  });

  it('does not emit defs export when $defs is absent', () => {
    const { code } = generate({ type: 'string' });
    expect(code).not.toContain('export const defs');
  });

  it('emits $def consts before the root schema export', () => {
    const { code } = generate({
      type: 'object',
      $defs: { Foo: { type: 'boolean' } },
      properties: {},
    });
    const defPos = code.indexOf('const FooSchema');
    const schemaPos = code.indexOf('export const schema');
    expect(defPos).toBeGreaterThan(-1);
    expect(schemaPos).toBeGreaterThan(defPos);
  });
});

// ---------------------------------------------------------------------------
// $ref resolution
// ---------------------------------------------------------------------------

describe('generateZodSourceFromJsonSchema - $ref resolution', () => {
  it('resolves #/$defs refs as direct variable references', () => {
    const { code } = generate({
      type: 'object',
      $defs: {
        Tag: { type: 'string' },
      },
      properties: {
        tag: { $ref: '#/$defs/Tag' },
      },
    });
    expect(code).toContain('get tag() { return TagSchema');
  });

  it('handles circular $ref via getter syntax (no z.lazy)', () => {
    const { code, diagnostics } = generate({
      type: 'object',
      $defs: {
        Node: {
          type: 'object',
          properties: {
            child: { $ref: '#/$defs/Node' },
          },
        },
      },
      properties: {
        root: { $ref: '#/$defs/Node' },
      },
    });
    expect(code).toContain('get child() { return NodeSchema');
    expect(code).toContain('get root() { return NodeSchema');
    expect(diagnostics.filter((d) => d.level === 'error')).toHaveLength(0);
  });

  it('emits diagnostic for unknown $def ref', () => {
    const { diagnostics } = generate({
      type: 'object',
      properties: {
        x: { $ref: '#/$defs/Missing' },
      },
    });
    expect(diagnostics.some((d) => d.code === 'missing-component-schema')).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// Full schema fixture (examples/schema.json shape)
// ---------------------------------------------------------------------------

describe('generateZodSourceFromJsonSchema - complex schema', () => {
  const schema = {
    type: 'object',
    $defs: {
      Address: {
        type: 'object',
        required: ['street', 'city'],
        properties: {
          street: { type: 'string' },
          city: { type: 'string' },
          zip: { type: 'string' },
        },
      },
      Person: {
        type: 'object',
        required: ['name'],
        properties: {
          name: { type: 'string' },
          age: { type: 'integer', minimum: 0 },
          address: { $ref: '#/$defs/Address' },
        },
      },
    },
    required: ['owner'],
    properties: {
      owner: { $ref: '#/$defs/Person' },
      guests: {
        type: 'array',
        items: { $ref: '#/$defs/Person' },
      },
    },
  };

  it('generates without errors', () => {
    const { diagnostics } = generate(schema);
    expect(diagnostics.filter((d) => d.level === 'error')).toHaveLength(0);
  });

  it('emits all $def schemas', () => {
    const { code } = generate(schema);
    expect(code).toContain('const AddressSchema =');
    expect(code).toContain('const PersonSchema =');
  });

  it('cross-references defs via getter syntax', () => {
    const { code } = generate(schema);
    expect(code).toContain('get address() { return AddressSchema');
    expect(code).toContain('get owner() { return PersonSchema');
  });

  it('exports defs with both names', () => {
    const { code } = generate(schema);
    expect(code).toContain('Address: AddressSchema');
    expect(code).toContain('Person: PersonSchema');
  });
});

// ---------------------------------------------------------------------------
// Title alias export
// ---------------------------------------------------------------------------

describe('generateZodSourceFromJsonSchema - title alias', () => {
  it('exports a named alias when root schema has a title', () => {
    const { code } = generate({ title: 'MyModel', type: 'object', properties: {} });
    expect(code).toContain('export { schema as MyModelSchema }');
  });

  it('does not emit alias when title is absent', () => {
    const { code } = generate({ type: 'object', properties: {} });
    expect(code).not.toContain('export { schema as');
  });

  it('sanitises title into a valid identifier', () => {
    const { code } = generate({ title: 'my-model 2', type: 'string' });
    expect(code).toContain('export { schema as my_model_2Schema }');
  });
});

// ---------------------------------------------------------------------------
// Options
// ---------------------------------------------------------------------------

describe('generateZodSourceFromJsonSchema - options', () => {
  it('alphabetical sorts properties', () => {
    const { code } = generate(
      {
        type: 'object',
        properties: {
          z_last: { type: 'string' },
          a_first: { type: 'string' },
        },
      },
      { alphabetical: true },
    );
    expect(code.indexOf('a_first')).toBeLessThan(code.indexOf('z_last'));
  });

  it('useDateCodecs emits codec helpers', () => {
    const { code } = generate({ type: 'string', format: 'date-time' }, { useDateCodecs: true });
    expect(code).toContain('isoDatetimeToDate');
    expect(code).toContain('z.codec(');
  });

  it('overrides replace specific pointers', () => {
    const { code } = generate(
      {
        type: 'object',
        $defs: { Status: { type: 'string' } },
        properties: {},
      },
      { overrides: { '#/$defs/Status': 'z.enum(["active", "inactive"])' } },
    );
    expect(code).toContain('z.enum(["active", "inactive"])');
  });

  it('strict mode throws on first error', () => {
    expect(() =>
      generateZodSourceFromJsonSchema(
        {
          type: 'object',
          properties: {
            x: { $ref: '#/$defs/DoesNotExist' },
          },
        },
        { strict: true },
      ),
    ).toThrow();
  });

  it('emits .default(value) for non-required properties with defaults by default', () => {
    const { code } = generate({
      type: 'object',
      properties: {
        retries: { type: 'integer', default: 3 },
      },
    });

    expect(code).toContain('retries: z.int().default(3)');
    expect(code).not.toContain('retries: z.int().optional()');
  });

  it('can disable default-value promotion explicitly', () => {
    const { code } = generate(
      {
        type: 'object',
        properties: {
          retries: { type: 'integer', default: 3 },
        },
      },
      { defaultNonNullable: false },
    );

    expect(code).toContain('retries: z.int().optional()');
    expect(code).not.toContain('retries: z.int().default(3)');
  });
});
// ---------------------------------------------------------------------------
// Zod Mini mode
// ---------------------------------------------------------------------------
describe('generateZodSourceFromJsonSchema - mini mode', () => {
  it('emits zod/mini import', () => {
    const { code } = generateZodSourceFromJsonSchema({ type: 'string' }, { useZodMini: true });
    expect(code).toContain("import * as z from 'zod/mini'");
    expect(code).not.toContain("import { z } from 'zod'");
  });

  it('emits .check() for string constraints', () => {
    const { code } = generateZodSourceFromJsonSchema(
      { type: 'string', minLength: 1, maxLength: 50 },
      { useZodMini: true },
    );
    expect(code).toContain('z.string().check(z.minLength(1), z.maxLength(50))');
  });

  it('emits z.optional() for optional properties', () => {
    const { code } = generateZodSourceFromJsonSchema(
      { type: 'object', properties: { name: { type: 'string' } } },
      { useZodMini: true },
    );
    expect(code).toContain('z.optional(z.string())');
    expect(code).not.toMatch(/\)\.optional\(\)/);
  });

  it('regular mode is unchanged', () => {
    const { code } = generateZodSourceFromJsonSchema({ type: 'string' });
    expect(code).toContain("import * as z from 'zod'");
    expect(code).not.toContain('zod/mini');
  });
});
