/**
 * JSON Schema → Zod source code generator.
 *
 * Unlike {@link generateZodSourceFromOpenApi}, this function works on a
 * standalone JSON Schema document (draft 2019-09 / 2020-12) that uses
 * `$defs` for named sub-schemas. `$ref`s of the form `#/$defs/Name` are
 * resolved and emitted as `z.lazy(() => NameSchema)` to safely handle
 * circular references.
 *
 * @module json-schema-source-generator
 */

import type {
  GenerateJsonSchemaZodSourceOptions,
  GenerateJsonSchemaZodSourceResult,
  OpenApiObject,
  PlainObject,
} from './types';
import { DiagnosticCollector } from './diagnostics-collector';
import { SchemaToZodConverter } from './schema-to-zod-converter';
import {
  escapeJsonPointer,
  isObject,
  sortKeys,
  toIdentifier,
  topoSortSchemaNames,
  toPropertyKey,
  unescapeJsonPointer,
} from './json-schema-utils';

/**
 * Generates TypeScript source code containing Zod schemas from a JSON Schema
 * document.
 *
 * Named definitions in `$defs` are emitted as individual `const` variables
 * (e.g. `const MyModelSchema = …`) so they can be referenced via
 * `z.lazy(() => MyModelSchema)`. The root schema is exported as `schema` and
 * all `$defs` are exported as `defs`.
 *
 * @param jsonSchema - A parsed JSON Schema document (object with optional `$defs`).
 * @param options - Generation options (defaults to strict mode).
 * @returns The generated source code and any diagnostics.
 *
 * @example
 * ```ts
 * import schema from './my-schema.json';
 * const { code } = generateZodSourceFromJsonSchema(schema);
 * await Bun.write('schemas.ts', code);
 * ```
 */
export function generateZodSourceFromJsonSchema(
  jsonSchema: unknown,
  options: GenerateJsonSchemaZodSourceOptions = {},
): GenerateJsonSchemaZodSourceResult {
  const diagnostics = new DiagnosticCollector(options.strict ?? true);

  // Extract $defs
  const defs: Record<string, PlainObject> = {};
  if (isObject(jsonSchema) && isObject(jsonSchema.$defs)) {
    for (const defName of Object.keys(jsonSchema.$defs)) {
      const def = jsonSchema.$defs[defName];
      if (isObject(def)) {
        defs[defName] = def;
      }
    }
  }

  // Build variable names for all $defs (used for z.lazy refs)
  const defVarNames = buildDefVarNames(defs);

  // Pass the JSON Schema document as the root for $ref traversal.
  // SchemaToZodConverter uses resolveRef() which just walks the object tree,
  // so any local $ref (including #/$defs/X) resolves correctly.
  const converter = new SchemaToZodConverter(
    jsonSchema as unknown as OpenApiObject,
    defVarNames,
    diagnostics,
    options.useDateCodecs ?? false,
    options.overrides ?? {},
    undefined,
    options.strictAdditionalProperties ?? true,
    options.alphabetical ?? false,
  );

  const bodyLines: string[] = [];

  // Emit $defs as named const variables in dependency-first order so that
  // direct variable references are always declared before use.
  const defOrder = topoSortSchemaNames(defs, (ref) => {
    const m = /^#\/\$defs\/([^/]+)$/.exec(ref);
    return m ? unescapeJsonPointer(m[1] ?? '') : undefined;
  });
  for (const defName of defOrder) {
    const varName = defVarNames[defName];
    const expr = converter.convert(defs[defName], `#/$defs/${escapeJsonPointer(defName)}`);
    bodyLines.push(`const ${varName} = ${expr};`);
  }

  if (defOrder.length > 0) {
    bodyLines.push('');
  }

  // Emit the root schema
  const rootExpr = converter.convert(jsonSchema, '#');
  bodyLines.push(`export const schema = ${rootExpr};`);

  // If the root schema has a title, export a named alias
  const rootTitle =
    isObject(jsonSchema) && typeof jsonSchema.title === 'string' ? jsonSchema.title : undefined;
  if (rootTitle) {
    const titleVarName = `${toIdentifier(rootTitle)}Schema`;
    bodyLines.push(`export { schema as ${titleVarName} };`);
  }

  // Emit a defs export so callers can access individual named schemas
  if (Object.keys(defs).length > 0) {
    bodyLines.push('');
    bodyLines.push('export const defs = {');
    for (const defName of sortKeys(defs)) {
      bodyLines.push(`  ${toPropertyKey(defName)}: ${defVarNames[defName]},`);
    }
    bodyLines.push('} as const;');
  }

  bodyLines.push('');

  const headerLines: string[] = [];
  headerLines.push('// Auto-generated by @saunos/openapi-to-zod.');
  headerLines.push("import { z } from 'zod';");

  const usedCodecs = converter.getUsedCodecs();
  if (usedCodecs.size > 0) {
    headerLines.push('');
    if (usedCodecs.has('datetime')) {
      headerLines.push(
        'const isoDatetimeToDate = z.codec(z.iso.datetime(), z.date(), { decode: (isoString) => new Date(isoString), encode: (date) => date.toISOString() });',
      );
    }
    if (usedCodecs.has('date')) {
      headerLines.push(
        'const isoDateToDate = z.codec(z.iso.date(), z.date(), { decode: (isoString) => new Date(isoString), encode: (date) => date.toISOString().slice(0, 10) });',
      );
    }
  }

  headerLines.push('');

  const code = `${[...headerLines, ...bodyLines].join('\n')}\n`;
  return { code, diagnostics: diagnostics.list() };
}

/**
 * Assigns unique TypeScript variable names to JSON Schema `$defs`.
 *
 * Each name is converted to a valid identifier via {@link toIdentifier} and
 * suffixed with `Schema`. Collisions are resolved by appending an index.
 */
function buildDefVarNames(defs: Record<string, PlainObject>): Record<string, string> {
  const used = new Set<string>();
  const mapping: Record<string, string> = {};

  for (const name of sortKeys(defs)) {
    const base = `${toIdentifier(name)}Schema`;
    let candidate = base;
    let index = 2;
    while (used.has(candidate)) {
      candidate = `${base}${index}`;
      index += 1;
    }
    used.add(candidate);
    mapping[name] = candidate;
  }

  return mapping;
}
